site_name: 'Witnet Protocol Documentation'
site_url: https://docs.witnet.io
copyright: © 2018-2021 The Witnet Community. Available under <a href="https://www.gnu.org/licenses/fdl-1.3.en.html" rel="license">GNU Free Documentation License v1.3</a>

nav:
  - Overview:
      - Ecosystem: index.md
      - What is Witnet?: overview/concepts.md
      - Software: overview/software.md
  - Running a Witnet node:
      - Quick Start Guide: try/run-a-node.md
      - Next Steps: try/next-steps.md
      - Hardware requirements: node-operators/hardware-requirements.md
      - Run as systemd service: node-operators/systemd-service.md
      - Run as docker-compose service: node-operators/docker-compose-service.md
      - Command Line Interface: node-operators/cli.md
      #- Use the Sheikah wallet / IDE: try/sheikah.md
  - Ethereum:
    - Price Feeds: ethereum/price-feeds.md
    - Addresses: ethereum/addresses.md
    - Connect your Ethereum contracts to any APIs: try/use-from-ethereum.md
    - Truffle Box Tutorial:
        - Introduction: tutorials/bitcoin-price-feed/introduction.md
        - 1. Create a new project: tutorials/bitcoin-price-feed/create-project.md
        - 2. Adding data sources: tutorials/bitcoin-price-feed/sources.md
        - 3. Define aggregator / tally: tutorials/bitcoin-price-feed/aggregations.md
        - 4. Fine-tune the request: tutorials/bitcoin-price-feed/fine-tuning.md
        - 5. Compile and try the request: tutorials/bitcoin-price-feed/compiling.md
        - 6. Write the Solidity contract: tutorials/bitcoin-price-feed/contract.md
        - 7. Deploy: tutorials/bitcoin-price-feed/migrations.md
        - Recap: tutorials/bitcoin-price-feed/recap.md
  - Other chains:
      - Boba (Layer 2):
          - Price Feeds: chains/boba/price-feeds.md
          - Addresses: chains/boba/addresses.md
      - Conflux Network:
          - Price Feeds: chains/conflux/price-feeds.md
          - Addresses: chains/conflux/addresses.md
  - Witnet-Rust Docs:
      - Integration guide: developer/integrations.md
      - Compile from source code: developer/from-source.md
      - Contributing: developer/contributing.md
      - Wallet API: developer/wallet-api.md
  - Protocol Docs:
      #- protocol/reputation.md
      - protocol/sortition.md
      #- protocol/transactions.md
      #- protocol/blocks.md
      - Witnet Requests:
          - Overview: protocol/data-requests/overview.md
          - Encoding: protocol/data-requests/radon-encoding.md
          - RNG:  protocol/data-requests/rng.md
      #- protocol/serialization.md
  #- Operator Docs:
      #- Run an Ethereum bridge: node-operators/ethereum-bridge.md
      #- Compilation: witnet-rust/compiling.md
      #- Configuration: witnet-rust/configuration.md
      #- Witnet-Rust JSON-RPC: node-operators/json-rpc.md
      #- Wallet API: node-operators/wallet-api.md
  - More:
      - overview/glossary.md

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.svg" alt="Witnet Logo'
  font: 'Almarai'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: 'teal'
      accent: 'teal'
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_name: 'witnet/documentation'
repo_url: 'https://github.com/witnet/documentation'
edit_uri: 'blob/master/docs'
remote_name: 'upstream'

extra:
  og_image: 'assets/images/logo-docs.png'
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/witnet'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/witnetio'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/witnet_io'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://youtube.com/witnetfoundation'
    - icon: 'fontawesome/brands/reddit'
      link: 'https://reddit.com/r/witnet'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
